### ISSUE TITLE
Checkout fails

### ISSUE THREAD

**Issue by Kroellie** [myparcelnl/magento#715]
### Plugin version

4.6.1

### Magento version

2.4.4

### PHP version

7.4

### What went wrong?

After updating from MyParcel plugin 4.5.0 to 4.6.1 during checkout the delivery options never show. The debug console is showing the message: e.split is not a function which got triggered in the myparcel.min.js file.

### Reproduction steps

1. Navigate to ...
2. Click on ...
3. See ...

**Comment by RichardPerdaan** [comment]
Solved in 4.7.0 of the MyParcel plugin
